/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'lindsaysmith' at '5/7/20 12:36 AM' with Gradle 3.2.1
 *
 * @author lindsaysmith, @date 5/7/20 12:36 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
